-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 10:08:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nuky
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nuky
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nuky` DEFAULT CHARACTER SET utf8 ;
USE `nuky` ;

-- -----------------------------------------------------
-- Table `nuky`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`category` ;

CREATE TABLE IF NOT EXISTS `nuky`.`category` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(50) NULL,
  `parent_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_category1_idx` (`parent_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `nuky`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nuky`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`post` ;

CREATE TABLE IF NOT EXISTS `nuky`.`post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NULL,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NULL,
  `publish_date` DATETIME NULL,
  `status` TINYINT NULL,
  `title` VARCHAR(200) NOT NULL,
  `excerpt` VARCHAR(200) NULL,
  `content` LONGTEXT NULL,
  `comment_count` BIGINT NOT NULL DEFAULT 0,
  `views` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_post_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `nuky`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuky`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`user` ;

CREATE TABLE IF NOT EXISTS `nuky`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `IP` VARCHAR(100) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `nuky`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`comment` ;

CREATE TABLE IF NOT EXISTS `nuky`.`comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `replied_comment_id` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `status` TINYINT NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_comment1_idx` (`replied_comment_id` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_comment1`
    FOREIGN KEY (`replied_comment_id`)
    REFERENCES `nuky`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `nuky`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `nuky`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuky`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`tag` ;

CREATE TABLE IF NOT EXISTS `nuky`.`tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nuky`.`post_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`post_tag` ;

CREATE TABLE IF NOT EXISTS `nuky`.`post_tag` (
  `post_id` BIGINT NOT NULL,
  `tag_id` BIGINT NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `fk_post_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_tag_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `nuky`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `nuky`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nuky`.`system_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nuky`.`system_settings` ;

CREATE TABLE IF NOT EXISTS `nuky`.`system_settings` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(255) NOT NULL,
  `setting_value` VARCHAR(255) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `setting_key_UNIQUE` (`setting_key` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
