spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: # git repo uri
          username:
          password:
  rabbitmq:
    host: localhost
    port: 5672
    username: nuky
    password: nuky
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
